### DISCUSSION TITLE
Authenticate to GH Package Registry

### DISCUSSION THREAD

**Discussion by kimegede** [ruby/setup-ruby#516] [Q&A] [answered]
Add possibility to pass a Personal Access Token to authenticate to GitHub Package Registry.

**Comment by dentarg** [comment]
You can just set the Bundler environment variable

**Reply by kimegede** [reply]
I'm still not sure which one, can you please explain with an example?

**Reply by dentarg** [reply, marked as answer]
Here's an example: https://github.com/84codes/actions/blob/76fd59f31d903b87b2bde515c8171e7ab30fa2ae/.github/workflows/ruby-ci.yml#L60-L66

Looks like you are missing the username when setting `BUNDLE_RUBYGEMS__PKG__GITHUB__COM`

**Reply by kimegede** [reply]
Thanks <3
Will get it tested out.

**Reply by kimegede** [reply]
Thank you a bunch @dentarg 🙇 👍

**Comment by kimegede** [comment]
Okay, I have tried with the following:
But still required token it set.
```yaml
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
        env:
          BUNDLE_GITHUB__COM: ${{ secrets.GH_PACKAGE_TOKEN }}:x-oauth-basic
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.GH_PACKAGE_TOKEN }}
```

Currently using:

```yaml
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          bundle config set --global rubygems.pkg.github.com ${{ secrets.GH_PACKAGE_TOKEN }}:x-oauth-basic
          gem install bundler
          bundle install --jobs 4 --retry 3
```
