### DISCUSSION TITLE
Required to update Github access token for Bundler in GH actions secrets after Ruby version change

### DISCUSSION THREAD

**Discussion by espen** [ruby/setup-ruby#604] [Q&A]
It seems like upgrading ruby version will somehow is unable to fetch the GH secret for BUNDLE_GITHUB__COM ENV var. Not sure if this a Github Actions issue or related to this project.

Recently my tests failed due to an issue with a secret token used for a private Github repo that I use my Gemfile. I am setting BUNDLE_GITHUB__COM from GH Action Secrets. This works however suddenly it failed. After some debugging I gave up and created a new token. Tests turned green. That was two weeks ago. Now it happened again. I though maybe it was a short lived token, but no. Then I discovered my last failed test was a Ruby version upgrade. As was this one. So I tried just reentering the same token in GH secrets. Green tests.

Some info from my rubyonrails.yml:

```
 env:
      BUNDLE_GITHUB__COM: x-access-token:${{ secrets.BUNDLE_GITHUB__COM }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
```
