### DISCUSSION TITLE
Ruby 3.4 on ios

### DISCUSSION THREAD

**Discussion by sifourquier** [ruby/setup-ruby#770] [Q&A]
I have try ruby 3.4 on "runs-on: macos-14"

I have a fail.

```
Run ruby/setup-ruby@v1
Modifying PATH
Downloading Ruby
Extracting  Ruby
Print Ruby version
Installing Bundler
> bundle install
/Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/bin/bundle config --local path /Users/runner/work/yakbike-app/yakbike-app/ios/vendor/bundle
/Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/lib/ruby/gems/3.4.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/error.rb:105:in '<class:Thor>': uninitialized constant DidYouMean::SPELL_CHECKERS (NameError)

    DidYouMean::SPELL_CHECKERS.merge!(
              ^^^^^^^^^^^^^^^^
Did you mean?  DidYouMean::SpellChecker
	from /Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/lib/ruby/gems/3.4.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/error.rb:1:in '<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/lib/ruby/gems/3.4.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/base.rb:3:in 'Kernel#require_relative'
	from /Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/lib/ruby/gems/3.4.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/base.rb:3:in '<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/lib/ruby/gems/3.4.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor.rb:1:in 'Kernel#require_relative'
	from /Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/lib/ruby/gems/3.4.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor.rb:1:in '<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/lib/ruby/gems/3.4.0/gems/bundler-2.2.26/lib/bundler/vendored_thor.rb:8:in 'Kernel#require_relative'
	from /Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/lib/ruby/gems/3.4.0/gems/bundler-2.2.26/lib/bundler/vendored_thor.rb:8:in '<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/lib/ruby/gems/3.4.0/gems/bundler-2.2.26/lib/bundler/friendly_errors.rb:3:in 'Kernel#require_relative'
	from /Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/lib/ruby/gems/3.4.0/gems/bundler-2.2.26/lib/bundler/friendly_errors.rb:3:in '<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/lib/ruby/gems/3.4.0/gems/bundler-2.2.26/exe/bundle:32:in 'Kernel#require_relative'
	from /Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/lib/ruby/gems/3.4.0/gems/bundler-2.2.26/exe/bundle:32:in '<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/bin/bundle:25:in 'Kernel#load'
	from /Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/bin/bundle:25:in '<main>'
Error: The process '/Users/runner/hostedtoolcache/Ruby/3.4.2/arm64/bin/bundle' failed with exit code 1
```

I have try with ruby 3.4 and 3.4.2.

I'm not sur is a bug of ruby? or setup-ruby? or other?

Has anyone tested ruby ​​3.4 on macOS?

my workflows
```
name: Deploy_IOS

on:
  release:
      types: [ published ]
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-14
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Get build number
        uses: mlilback/build-number@v1
        with:
          # GITHUB_RUN_NUMBER was reset when renaming this GitHub Actions workflow.
          # That breaks the sequence of build numbers required on Android Play Store,
          # so the build number is computed by adding 157, which was the latest number
          # deployed on the store when adding this fix.
          # The correct build number is generated in $BUILD_NUMBER
          # See https://github.com/orgs/community/discussions/26709
          base: 157
          run-id: "${{ github.run_number }}"

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "latest"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'master'
          cache: true

      - name: Install fastlane for iOS
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
          bundler-cache: true
          working-directory: ios

      - name: Install Android keystore
        run: |
          echo $ANDROID_KEYSTORE_JKS_BASE64 | base64 --decode > $HOME/keystore.jks
          echo "ANDROID_KEYSTORE_PATH=$HOME/keystore.jks" >> "$GITHUB_ENV"
        env:
          ANDROID_KEYSTORE_JKS_BASE64: ${{ secrets.ANDROID_KEYSTORE_JKS_BASE64 }}

      - name: Build iOS
        run: |
          make ios.release

      - name: Deploy iOS to Apple TestFlight
        run: |
          cd ios
          bundle exec fastlane beta
        env:
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
```
