### ISSUE TITLE
Feature request: Support env for bundler, and allow customising cache key.

### ISSUE THREAD

**Issue by JonRowe** [ruby/setup-ruby#112]
We're running into issues with RSpec builds where the cache has versions of gems different to our gem files.

We're specifying versions of gems via environment variables to build up matrices, for example RSpec Rails tests various combinations of Rails and running into problems with the cache already having versions of these gems from bundle installing the default.

It'd be useful to support env for the bundle install for the cache, so we can cache these matrix sets, and prehaps to either automatically cache by the matrix job, or prehaps more realistically, manually add a salt so we can differentiate them.

**Comment by JonRowe** [comment]
Example from rspec-mocks using different versions of diff-lcs https://github.com/rspec/rspec-mocks/runs/1435790514?check_suite_focus=true

**Comment by benoittgt** [comment]
Here is an example: https://github.com/rspec/rspec-rails/runs/1414567253?check_suite_focus=true

With this config: https://github.com/rspec/rspec-rails/blob/2270be597a1ab5a7f6e4823166594fc323f0e6c8/.github/workflows/ci.yml#L93-L94

**Comment by MSP-Greg** [comment]
Maybe add an action input, something like `cache-key`?  If used, the action would retrieve the cache, and save it later, but not perform a `bundle install`?  Kind of assumes folder location, etc..

I think the current implementation was setup to save a few workflow steps, while mimicking what Travis did.  You might consider using [actions/cache](https://github.com/actions/cache) directly?

**Comment by eregon** [comment]
Can you set these variables before `- uses: ruby/setup-ruby@v1`?
Then it should just work.

Any `bundle` command without the env var set would anyway fail, so it seems best practice to set the env var(s) from the start.

Where are the env vars set currently?

**Comment by eregon** [comment]
The cache will be based on the Gemfile.lock, so there should be no need to tweak or work around the caching.
But of course, the `bundle install` done by `setup-ruby` needs to have the right env vars if you depend on env vars in the Gemfile.

**Comment by eregon** [comment]
I'm pretty sure the cache is not the issue here, for instance on https://github.com/rspec/rspec-mocks/runs/1435790514?check_suite_focus=true#step:3:20 you can see `bundle lock` is run first (before even fetching the cache), and that creates the Gemfile.lock, and because of the output later, we know that `diff-lcs 1.4.4` was chosen.
Which means, even though the job specified
```yaml
          - ruby: 2.7
            name_extra: "with diff-lcs 1.3"
            env:
              DIFF_LCS_VERSION: "~> 1.3.0"
```
It seems the action didn't see that variable, which is surprising and could be a bug of GitHub Actions.

Could you add a debug print of `ENV['DIFF_LCS_VERSION']` in the Gemfile?

**Comment by JonRowe** [comment]
Moving the env from run to the step seems to have solved it automatically

**Comment by eregon** [comment]
BTW, probably unrelated, but the syntax here looks incorrect: https://github.com/rspec/rspec-mocks/actions/runs/376148102/workflow#L30-L32

**Comment by eregon** [comment]
@JonRowe  Do you mean using `echo VAR=val >> $GITHUB_ENV` as an extra step before, instead of `env` on the job level?
That would still very likely be a bug upstream, so it would be great if you can file a bug at https://github.com/actions/runner/issues.

**Comment by JonRowe** [comment]
The later, sorry I find the github docs really confusing about what is actually allowed where, we did try setting the env for the entirely of the build before, but it seems it does allow it to be in the job "inner"

**Comment by eregon** [comment]
Ah, I see, the problem was:
(from https://github.com/rspec/rspec-mocks/actions/runs/376148102/workflow)
```yaml
jobs:
  test:
    name: Ruby ${{ matrix.ruby }} ${{ matrix.name_extra || '' }}
    runs-on: ${{ matrix.os || 'ubuntu-20.04' }}
    strategy:
      matrix:
        ruby:
          - 3.0.0-preview1
          - 2.7
          - 2.6
          - 2.5
          - 2.4
          - 2.3
          - 2.2
          - 2.1.9
          - ruby-head
        env:
          -
            DIFF_LCS_VERSION: "> 1.4.3"
        include:
          - ruby: jruby-9.2.13.0
            env:
              JRUBY_OPTS: "--dev"
          - ruby: jruby-9.1.17.0
            bundler: 1
            os: ubuntu-18.04
            env:
              JRUBY_OPTS: "--dev"
          - ruby: 2.7
            name_extra: "with diff-lcs 1.3"
            env:
              DIFF_LCS_VERSION: "~> 1.3.0"
          - ruby: 2.7
            name_extra: "with diff-lcs 1.4.3"
            env:
              DIFF_LCS_VERSION: "1.4.3"
      fail-fast: false
    continue-on-error: ${{ matrix.allow_failure || endsWith(matrix.ruby, 'head') }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler: ${{ matrix.bundler || 2 }}
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: script/update_rubygems_and_install_bundler
        env: ${{ matrix.env }}
      - run: script/clone_all_rspec_repos
        env: ${{ matrix.env }}
      - run: bundle install --binstubs --standalone
        env: ${{ matrix.env }}
      - run: script/run_build
        env: ${{ matrix.env }}
```

So that sets the env for each `run` step, but not for `uses: ruby/setup-ruby`.

Anything defined under `matrix` just creates the number of combinations from the values, but these values are not magically set, no matter the name. So `env: ${{ matrix.env }}` is what was missing:
```yaml
    continue-on-error: ${{ matrix.allow_failure || endsWith(matrix.ruby, 'head') }}
    env: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler: ${{ matrix.bundler || 2 }}
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: script/update_rubygems_and_install_bundler
      - run: script/clone_all_rspec_repos
      - run: bundle install --binstubs --standalone
      - run: script/run_build
```
