### ISSUE TITLE
bundler-cache with sassc leads to [BUG] Illegal instruction at 0x00007f9xxx FFI error

### ISSUE THREAD

**Issue by hidde-jan** [ruby/setup-ruby#141]
I ran into a bug where loading sassc leads to a ffi error. At first, the following action setup ran fine, however, after removing installation of bundler and the extra bundle install step, all subsequent runs of the actions failed, because of an illegal instruction in libffi. The error occurred in the db setup step. This seems to be the case because there is a non portable cached binary for sassc in the bundler cache.

Removing the bundler-cache fixed my pipeline.

Action setup:

```yaml
# This is a basic workflow to help you get started with Actions

name: Rails CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:11-2.5
        env:
          POSTGRES_USER: rails_github_actions
          POSTGRES_DB: rails_github_actions_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.13.0
      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          npm ci
      - name: Setup test database
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://rails_github_actions:postgres@localhost:${{ job.services.postgres.ports[5432] }}/rails_github_actions_test
        run: |
          bundle exec rails db:test:prepare
      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://rails_github_actions:postgres@localhost:${{ job.services.postgres.ports[5432] }}/rails_github_actions_test
        run: |
          bundle exec rails test
```

Error:

```
bundle exec rails db:test:prepare
3
  shell: /bin/bash -e {0}
4
  env:
5
    RAILS_ENV: test
6
    DATABASE_URL: ***localhost:5432/rails_github_actions_test
7
/home/runner/work/portfolio-api/portfolio-api/vendor/bundle/ruby/2.6.0/gems/ffi-1.12.2/lib/ffi/library.rb:112: [BUG] Illegal instruction at 0x00007f98039729b0
8
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
9

10
-- Control frame information -----------------------------------------------
11
c:0067 p:---- s:0332 e:000331 CFUNC  :open
12
c:0066 p:0022 s:0326 e:000325 BLOCK  /home/runner/work/portfolio-api/portfolio-api/vendor/bundle/ruby/2.6.0/gems/ffi-1.12.2/lib/ffi/library.rb:112 [FINISH]
13
c:0065 p:---- s:0317 e:000316 CFUNC  :each
14
c:0064 p:0113 s:0313 e:000312 BLOCK  /home/runner/work/portfolio-api/portfolio-api/vendor/bundle/ruby/2.6.0/gems/ffi-1.12.2/lib/ffi/library.rb:109 [FINISH]
15
c:0063 p:---- s:0306 e:000305 CFUNC  :map
16
c:0062 p:0069 s:0302 e:000301 METHOD /home/runner/work/portfolio-api/portfolio-api/vendor/bundle/ruby/2.6.0/gems/ffi-1.12.2/lib/ffi/library.rb:99
17
c:0061 p:0079 s:0295 e:000294 CLASS  /home/runner/work/portfolio-api/portfolio-api/vendor/bundle/ruby/2.6.0/gems/sassc-2.2.1/lib/sassc/native.rb:11
18
c:0060 p:0007 s:0291 e:000290 CLASS  /home/runner/work/portfolio-api/portfolio-api/vendor/bundle/ruby/2.6.0/gems/sassc-2.2.1/lib/sassc/native.rb:6
19
c:0059 p:0014 s:0288 e:000287 TOP    /home/runner/work/portfolio-api/portfolio-api/vendor/bundle/ruby/2.6.0/gems/sassc-2.2.1/lib/sassc/native.rb:5 [FINISH]
20
c:0058 p:---- s:0285 e:000284 CFUNC  :require_relative
```
