### ISSUE TITLE
Allow using bundler-cache: true without deployment

### ISSUE THREAD

**Issue by davidwessman** [ruby/setup-ruby#153]
Hello!
I recently started updating my workflows to use the new `bundler-cache` option and it works great.
Then I ran into an error with this workflow where I update my Gemfile after setting up ruby.

<details>
  <summary>Github action workflow</summary>
  
```yaml
name: Update next

on:
  pull_request:
    paths:
      - "Gemfile.lock"

jobs:
  update:
    runs-on: ubuntu-20.04

    env:
      BUNDLE_GEMFILE: Gemfile.next

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.DUAL_BOOT_APP_ID }}
          private_key: ${{ secrets.DUAL_BOOT_PRIVATE_KEY }}

      - uses: actions/checkout@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Update Gemfile.next
        run: |
          bundle update --minor --conservative

      - uses: EndBug/add-and-commit@v7
        with:
          add: Gemfile.next.lock
          message: "Automatically bump next"
```

</details>

## Error

>You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.next.lock to version control.
If this is a development machine, remove the
/home/runner/work/uppstyrt/uppstyrt/Gemfile.next freeze
by running `bundle config --delete deployment`.

Would there be any way to use `bundler-cache: true` and be allowed to update Gemfile?
I tried adding `BUNDLER_DEPLOYMENT=false` but it did not make any difference.
