### ISSUE TITLE
This actions changes the output of future hashFiles calls

### ISSUE THREAD

**Issue by anark** [ruby/setup-ruby#154]
Hi there,
When using this action along with actions-cache this action seems to change the hashFiles output.  For example if I have the following workflow
```
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock') }}
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
```

The `hashFiles('**/yarn.lock')` will correctly match the hash made in other actions, however if I change the order
```
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock') }}
```

Then `hashFiles('**/yarn.lock')` will be a different hash and will no longer match the hash generated by other actions.
