### ISSUE TITLE
Missing file: .../ruby-install-builder/releases/download/builds-newer-openssl/ruby-2.7-ubuntu-18.04.tar.gz

### ISSUE THREAD

**Issue by anitagraham** [ruby/setup-ruby#159]
I am running with this main.yml (edit for brevity)
```
name: CI
on: [push]

jobs:
  test:
    strategy:
      matrix:
        database: [ mysql, postgresql ]
        extension: [ core, dragonfly, images, pages, resources ]
        ruby: [ 2.7, 2.6 ]
      fail-fast: false
      max-parallel: 10
    runs-on: ubuntu-latest

    env:
      BUNDLE_JOBS: 4
      BUNDLE_PATH: vendor/bundle
      CI: true
      DB: ${{ matrix.database }}
      MYSQL_PASSWORD: root
      PGHOST: localhost
      PGUSER: postgres
      RAILS_ENV: test

    name: ${{ matrix.extension }} ${{ matrix.ruby }} ${{ matrix.database }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1.0.0
        with:
          ruby-version: ${{ matrix.ruby }}
... this is as far as it gets ...
```

This  is the result:
```
Run ruby/setup-ruby@v1.0.0
  with:
    ruby-version: 2.7
  env:
    BUNDLE_JOBS: 4
    BUNDLE_PATH: vendor/bundle
    CI: true
    DB: mysql
    MYSQL_PASSWORD: root
    PGHOST: localhost
    PGUSER: postgres
    RAILS_ENV: test
https://github.com/eregon/ruby-install-builder/releases/download/builds-newer-openssl/ruby-2.7-ubuntu-18.04.tar.gz
Error: Unexpected HTTP response: 404
```

(Which, btw, is the same result I get if I try to get that file in a browser).

Thanks for any help you may offer,

Anita Graham
(and belated apologies for two empty issues a couple of weeks ago.  I seemed to have very unreliable fingers that day and eventually abandoned the keyboard altogether.)
