### ISSUE TITLE
Support for libreadline

### ISSUE THREAD

**Issue by pavanprakash21** [ruby/setup-ruby#160]
Hi, we use byebug in our test environment and it requires readline to work properly and I am sure there are many other famous gems out there that need this support. Is there any chance I can configure the setup to include libreadline-dev dependency? 
Or do I have to build ruby from scratch to support this use case?

**Comment by pavanprakash21** [comment]
Thanks @eregon for the reply. This is the error I am seeing

```
Sorry, you can't use byebug without Readline. To solve this, you need to
    rebuild Ruby with Readline support. If using Ubuntu, try `sudo apt-get
    install libreadline-dev` and then reinstall your Ruby.
SimpleCov failed with exit 1
Coverage report generated for Minitest to /home/runner/work/repo/repo/test/reports/coverage. 101489 / 221285 LOC (45.86%) covered.
/home/runner/work/repo/repo/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require': libreadline.so.7: cannot open shared object file: No such file or directory - /opt/hostedtoolcache/Ruby/2.4.1/x64/lib/ruby/2.4.0/x86_64-linux/readline.so (LoadError)
	from /home/runner/work/repo/repo/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/runner/work/repo/repo/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/runner/work/repo/repo/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
	from /home/runner/work/repo/repo/vendor/bundle/ruby/2.4.0/gems/byebug-11.1.3/lib/byebug/history.rb:4:in `<top (required)>'
	from /home/runner/work/repo/repo/vendor/bundle/ruby/2.4.0/gems/byebug-11.1.3/lib/byebug/interface.rb:4:in `require_relative'
	from /home/runner/work/repo/repo/vendor/bundle/ruby/2.4.0/gems/byebug-11.1.3/lib/byebug/interface.rb:4:in `<top (required)>'
	from /home/runner/work/repo/repo/vendor/bundle/ruby/2.4.0/gems/byebug-11.1.3/lib/byebug/core.rb:7:in `require_relative'
	from /home/runner/work/repo/repo/vendor/bundle/ruby/2.4.0/gems/byebug-11.1.3/lib/byebug/core.rb:7:in `<top (required)>'
	from /home/runner/work/repo/repo/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
	from /home/runner/work/repo/repo/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
```

Then I tried to install `libreadline-dev` before setting up ruby using the action but it still resulted in the same error

**Comment by pavanprakash21** [comment]
For further context, I am trying to use ruby 2.4.1 in ubuntu 20.04

**Comment by eregon** [comment]
Could you share a complete workflow to reproduce?

**Comment by eregon** [comment]
As far as I can see, `/opt/hostedtoolcache/Ruby/2.4.1/x64/lib/ruby/2.4.0/x86_64-linux/readline.so` exists so `libreadline.so.7` must be missing on the system you are running.
GitHub-hosted runners seem to already have libreadline installed.

**Comment by pavanprakash21** [comment]
Sure. Here's the workflow

```yaml
---
name: Test

on: [push]

jobs:
  test:
    name: Build
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: docksal/mysql:5.6-edge
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=1s
          --health-timeout=3s
          --health-retries=10
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=1s
          --health-timeout=3s
          --health-retries=10

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup SSH for local repo pulls
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_TO_PULL_PRIVATE_REPOS }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          ImageOS: ubuntu18
        with:
          ruby-version: 2.4.1
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |-
          sudo apt-get -yqq install patch ruby-dev libreadline-dev zlib1g-dev liblzma-dev procps \
            imagemagick fontconfig fonts-indic fonts-nanum fonts-nanum-extra
          yarn install --check-files --pure-lockfile

      - name: Setup Test Database
        env:
          RAILS_ENV: test
          REDIS_SERVER: localhost
          MYSQL_SERVER: 0.0.0.0
          MYSQL_USER: root
          MYSQL_PASSWORD: password
        run: |-
          cp ci/application.ci.yml config/application.yml
          cp ci/database.ci.yml config/database.yml
          bundle exec rails db:create db:schema:load db:seed_fu db:seed

      - name: Run Tests
        env:
          RAILS_ENV: test
          REDIS_SERVER: localhost
          MYSQL_SERVER: 0.0.0.0
          MYSQL_USER: root
          MYSQL_PASSWORD: password
        run: |
          bundle exec rails factory_bot:lint
          bundle exec rails test

```

I couldn't find libreadline in https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md. So, installed it manually. 

Looking back at it, has it got something to do with `env: ImageOS: ubuntu18`?
