### ISSUE TITLE
Bundle does not support x86_64-linux

### ISSUE THREAD

**Issue by trigri1** [ruby/setup-ruby#177]
Hi!
I am unsing setup-ruby to cache the bundle but its not working on Ubuntu platform. Here is my workflow:

```
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby (Cache and Install bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
      - run: bundle exec rake
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Unit Tests
        run: |
          bundle exec fastlane unit_test
```

The error I am getting is this:
```
  Your bundle only supports platforms ["universal-darwin-20"] but your local
  platform is x86_64-linux. Add the current platform to the lockfile with `bundle
  lock --add-platform x86_64-linux` and try again.
  Took   0.81 seconds
Error: The process '/opt/hostedtoolcache/Ruby/2.6.7/x64/bin/bundle' failed with exit code 16
```

Why it does not support all the platforms? Thanks
