### ISSUE TITLE
JRuby on Windows: "bundler: command not found: rake"

### ISSUE THREAD

**Issue by dentarg** [ruby/setup-ruby#18]
[Actions config used](https://github.com/dentarg/dyno_metadata/blob/9cf668d7c1cd0b013ae6d4da49237eff4a84d9bc/.github/workflows/ruby.yml):

```yaml
jobs:
  build:
    name: '${{ matrix.os }}: ${{ matrix.ruby }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        ruby: [ 2.4, 2.5, 2.6, 2.7, jruby, truffleruby ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: ruby -v
    - run: bundle install --jobs 4 --retry 3
    - run: bundle exec rake
```

Output from the [`bundle exec rake` step]( https://github.com/dentarg/dyno_metadata/runs/433556352?check_suite_focus=true#step:6:4)

```
Run bundle exec rake
  bundle exec rake
  shell: C:\Program Files\PowerShell\6\pwsh.EXE -command ". '{0}'"
bundler: command not found: rake
Install missing gem executables with `bundle install`
##[error]Process completed with exit code 1.
```

The `bundle install` step before [do install `rake`](https://github.com/dentarg/dyno_metadata/runs/433556352?check_suite_focus=true#step:5:7)

I assume JRuby on Windows should work out-of-the-box, right? Am I doing something wrong?

I saw #12, so I checked the asciidoctor-epub3 repo, they are [installing bundler themselves](https://github.com/asciidoctor/asciidoctor-epub3/blob/ad30eb3afffb529ea3158a04ea6a9afd1dc71263/.github/workflows/ci.yml#L45), maybe that makes a difference somewhere
