### ISSUE TITLE
Can't bundle with ruby 3.0

### ISSUE THREAD

**Issue by jlntrt** [ruby/setup-ruby#184]
Hey all,

I have an issue with bundling a rails app with ruby 3.0. The ruby version is not fixed within the Gemfile and I can't see the reason. This is my configuration:

```yaml
name: Rspec
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      PGHOST: localhost
      PGUSER: postgres
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:10.6
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        ruby: [2.5, '3.0']
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Setup App
      run: sudo apt-get -y install libpq-dev
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run yarn
      run: yarn
    - name: Setup database
      run: |
        bin/rails db:setup
    - name: Run rspec
      run: bundle exec rspec
```

The matrix runner with ruby 3.0 always aborts with this output:

```
Run ruby/setup-ruby@v1
Installing Bundler
bundle install
Error: The process '/opt/hostedtoolcache/Ruby/3.0.1/x64/bin/bundle' failed with exit code 5
```

The ruby 2.5 matrix runner seems to work and starting bundling, but aborts when the ruby 3.0 runner breaks.
Can anyone give me a hint? Many thanks! :)
