### ISSUE TITLE
Bundle install starts failing without any change

### ISSUE THREAD

**Issue by uxxman** [ruby/setup-ruby#185]
Bundle install starts failing suddenly without any change to the workflow. Its fails to fetch gems that are present in rubygems.

Workflow file
```yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get -yqq install libpq-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 1

      - name: Rubocop
        run: bundle exec rubocop

      - name: Brakeman
        run: bundle exec brakeman

      - name: Bundler-Audit
        run: bundle exec bundler-audit

      - name: Test
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          bundle exec rails db:test:prepare
          bundle exec rspec spec
```

## Backtrace
  
  ```
  Gem::RemoteFetcher::FetchError: bad response Service Not Found 500 (https://rubygems.org/gems/method_source-1.0.0.gem)
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/3.0.0/rubygems/remote_fetcher.rb:239:in `fetch_http'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/3.0.0/rubygems/remote_fetcher.rb:255:in `fetch_path'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/3.0.0/rubygems/remote_fetcher.rb:292:in `cache_update_path'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/3.0.0/rubygems/remote_fetcher.rb:153:in `download'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/rubygems_integration.rb:527:in `block in download_gem'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/retry.rb:40:in `run'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/retry.rb:30:in `attempt'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/rubygems_integration.rb:526:in `download_gem'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:506:in `download_gem'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:447:in `fetch_gem'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:138:in `install'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/installer/gem_installer.rb:67:in `install'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/installer/gem_installer.rb:18:in `install_from_spec'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/worker.rb:62:in `apply_func'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/worker.rb:57:in `block in process_queue'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/worker.rb:54:in `loop'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/worker.rb:54:in `process_queue'
    /opt/hostedtoolcache/Ruby/3.0.1/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
  ```
  
  ## Environment
  
  ```
  Bundler       2.2.15
    Platforms   ruby, x86_64-linux
  Ruby          3.0.1p64 (2021-04-05 revision 0fb782ee38ea37fd5fe8b1f775f8ad866a82a3f0) [x86_64-linux]
    Full Path   /opt/hostedtoolcache/Ruby/3.0.1/x64/bin/ruby
    Config Dir  /opt/hostedtoolcache/Ruby/3.0.1/x64/etc
  RubyGems      3.2.15
    Gem Home    /home/runner/work/backend-api/backend-api/vendor/bundle/ruby/3.0.0
    Gem Path    /home/runner/work/backend-api/backend-api/vendor/bundle/ruby/3.0.0
    User Home   /home/runner
    User Path   /home/runner/.local/share/gem/ruby/3.0.0
    Bin Dir     /home/runner/work/backend-api/backend-api/vendor/bundle/ruby/3.0.0/bin
  OpenSSL       
    Compiled    OpenSSL 1.1.1f  31 Mar 2020
    Loaded      OpenSSL 1.1.1f  31 Mar 2020
    Cert File   /usr/lib/ssl/cert.pem
    Cert Dir    /usr/lib/ssl/certs
  Tools         
    Git         2.31.1
    RVM         not installed
    rbenv       not installed
    chruby      not installed
  ```
  
  ## Bundler Build Metadata
  
  ```
  Built At          2021-03-19
  Git SHA           3dbcc68293
  Released Version  true
  ```
  
  ## Bundler settings
  
  ```
  path
    Set for your local app (/home/runner/work/backend-api/backend-api/.bundle/config): "/home/runner/work/backend-api/backend-api/vendor/bundle"
  deployment
    Set for your local app (/home/runner/work/backend-api/backend-api/.bundle/config): true
  jobs
    Set for your local app (/home/runner/work/backend-api/backend-api/.bundle/config): 4
  ```
