### ISSUE TITLE
What about bundle config?

### ISSUE THREAD

**Issue by stereobooster** [ruby/setup-ruby#189]
What do you think about this proposal:

```yaml
- name: Set up Ruby
  uses: ruby/setup-ruby@v1
  config:
    name1: value1
    name2: value2
```

It would be useful for using private registries, like gemfury

**Comment by eregon** [comment]
Don't `BUNDLE_*` environment variables work for that?
See https://github.com/ruby/setup-ruby#bundle-config

**Comment by stereobooster** [comment]
@eregon probably they do and I didn't read documentation attentively. Thank you for the hint

**Comment by stereobooster** [comment]
I can't make it work

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      "BUNDLE_https://gem.fury.io/****/": ${{secrets.GEMFURY_TOKEN}}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          bundler: 2.2.0
```

I get forbidden error from gemfury, so I doesn't pickup value
