### ISSUE TITLE
Error: Version 2.6.7 not found

### ISSUE THREAD

**Issue by timimsms** [ruby/setup-ruby#203]
In the past few days, it seems there has been an update and Ruby 2.6.7 cannot be installed.

I'm seeing the following error:

```
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
Error: Version 2.6.7 not found
```

However, in the latest release it looks like Ruby 2.6.8 was added but I'm not seeing 2.6.7 removed.

Can you let us know if 2.6.7 should be supported at this time?

Run info:
- code is behind a private repo
- link is also in a private Github Actions project
- command of the workflow is below
- we are running this on Github Actions / on github.com.

Workflow of the step that is failing is provided below:

```
jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Bundler
        run: gem install bundler:2.2.4
      - name: Bundle Install
        run: bundle install
      - name: Check code
        run: bundle exec rubocop
```

Ruby Version is 2.6.7
