### ISSUE TITLE
Override .ruby-version file in matrix build?

### ISSUE THREAD

**Issue by dmolesUC** [ruby/setup-ruby#212]
I have 2.7 set in [`.ruby-version`](https://github.com/BerkeleyLibrary/marc/blob/d79d1eb24dca46a3004467224caf03219e3af711/.ruby-version) so an IDE (IDEA/RubyMine) can auto-detect it, but I want to build my project against both 2.7 and 3.x. In my [workflow](https://github.com/BerkeleyLibrary/marc/blob/5710acb7038813e335bc0b4ef1cdd3995f6a6afb/.github/workflows/build.yml) I have:

```yml
matrix:
  os: [ ubuntu-latest, macos-latest ]
  ruby-version: [ '2.7', '3.0' ]
```

but it seems like `.ruby-version` takes precedence, and the value set in the matrix is ignored. Is this intentional? Is there any way around it? Or am I just doing something wrong?

<img width="558" alt="Screen Shot 2021-08-19 at 12 33 22 PM" src="https://user-images.githubusercontent.com/10374934/130133172-75d7b50b-def5-4784-b9d3-16bece7b4881.png">

(screenshot from [job log](https://github.com/BerkeleyLibrary/marc/runs/3375410183?check_suite_focus=true))

**Comment by eregon** [comment]
It's already the case, it's a problem of your workflow:
```
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ruby-version: [ '2.7', '3.0' ]
...
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
```
matrix.ruby vs matrix.ruby-version
