### ISSUE TITLE
unable to provide config for bundler to connect to local gemstore

### ISSUE THREAD

**Issue by aswerlein511** [ruby/setup-ruby#214]
I am trying to use the caching feature of ruby/setup-ruby@v1 using the following. code:

```
  name: Setup Ruby

        uses: ruby/setup-ruby@v1

        env:

          BUNDLER_UPSTART__JFROG__IO: user:pass

        with:

          ruby-version: 2.7.2

          bundler-cache: true

          working-directory: ./project_root
```

however, when it runs the bundle install from the working-directory the credentials provide in the env directive are not set, and it fails when trying to connect.  

Is there a way to run bundle config and pass those values in?
