### ISSUE TITLE
bundler-cache error: underlying system error is Errno::ENAMETOOLONG: File name too long

### ISSUE THREAD

**Issue by aliwatters** [ruby/setup-ruby#217]
Hi -- trying to utilize the `bundler-cache:true` feature in `ruby/setup-ruby@v1` I ran in to this.

```
There was an error accessing
`/home/runner/.bundle/cache/compact_index/rubygems.pkg.github.com.***.443.<long-hash>/info`.
  The underlying system error is Errno::ENAMETOOLONG: File name too long @  dir_s_mkdir
```

Any advice appreciated.

from `.github/workflows/ci.yml`
```
jobs:
  build:
    runs-on: ubuntu-latest
    name: Set ruby version and cache dependencies
    outputs:
      ruby-version: ${{ steps['rvm'].outputs['RUBY-VERSION'] }}
    steps:
      - uses: actions/checkout@v2

      - name: Read .ruby-version
        run: echo ::set-output name=RUBY-VERSION::$(cat .ruby-version) # 2.6.5
        id: rvm

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${{ steps.rvm.outputs.RUBY-VERSION }}'
          bundler-cache: true
      
      - name: Info
        run: bundle env
```

output from action > setup ruby (hashes replaced)
```
  bundle install
  /opt/hostedtoolcache/Ruby/2.6.5/x64/bin/bundle config --local path /home/runner/work/<project>/<project>/vendor/bundle
  /opt/hostedtoolcache/Ruby/2.6.5/x64/bin/bundle config --local deployment true
  Cache key: setup-ruby-bundler-cache-v3-ubuntu-20.04-ruby-2.6.5-Gemfile.lock-1234567890123456890123456789012345678901234568901234567890123456
  /opt/hostedtoolcache/Ruby/2.6.5/x64/bin/bundle install --jobs 4
  [DEPRECATED] Your lockfile contains a single rubygems source section with multiple remotes, which is insecure. Make sure you run `bundle install` in non frozen mode and commit the result to make your lockfile secure.

  There was an error accessing
  `/home/runner/.bundle/cache/compact_index/rubygems.pkg.github.com.***.443.12345678901234568901234567890123/info`.
  The underlying system error is Errno::ENAMETOOLONG: File name too long @
  dir_s_mkdir -
  /home/runner/.bundle/cache/compact_index/rubygems.pkg.github.com.***.443.12345678901234568901234567890123
  Took   1.44 seconds
Error: The process '/opt/hostedtoolcache/Ruby/2.6.5/x64/bin/bundle' failed with exit code 32
```
