### ISSUE TITLE
Broken Ruby archive

### ISSUE THREAD

**Issue by tstrass** [ruby/setup-ruby#219]
Ruby [ruby-2.7.3-ubuntu-18.04.tar.gz](https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-2.7.3-ubuntu-18.04.tar.gz) is seemingly broken. I cannot download it from my browser, and my workflows ([example](https://github.com/SaraAlert/SaraAlert/pull/1068/checks?check_run_id=3656787771)) are getting 403 errors trying to download it.

Here is the relevant step from the example workflow:
```yaml
- name: Setup Ruby
  uses: ruby/setup-ruby@v1
  with:
    ruby-version: 2.7.3
```
