### ISSUE TITLE
cache breaks with private packages

### ISSUE THREAD

**Issue by modosc** [ruby/setup-ruby#222]
whenever `Gemfile.lock` changes, the first action run always fails, but the second succeeds.  we've seen this with prs from `dependabot` as well as prs opened by humans. 

if `Gemfile.lock` does not change then there's no issue. 

we have two different workflows with this issue - both are identical except for the last step (`bundle exec brakeman -q` vs `bundle exec rubocop`)
```yml
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: Linter

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
        env:
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.BUNDLE_RUBYGEMS__PKG__GITHUB__COM }}

      - name: Run brakeman
        run: |
          bundle exec brakeman -q
```
the first run will always fail:
![image](https://user-images.githubusercontent.com/2231664/134955972-7a66a8cb-2437-4f3d-b73a-818a9624780d.png)

but re-running manually always works:
![image](https://user-images.githubusercontent.com/2231664/134956016-f85afbfa-663f-4a9a-a012-ea7eec1feb83.png)

failing logs: [logs_588.zip](https://github.com/ruby/setup-ruby/files/7238184/logs_588.zip)
passing logs: [logs_779.zip](https://github.com/ruby/setup-ruby/files/7238185/logs_779.zip)

i can't link to the runs because they're from a private repo, do you need anything else here?
