### ISSUE TITLE
The environment variable ImageOS must be set (Self hosted runner)

### ISSUE THREAD

**Issue by jankeesvw** [ruby/setup-ruby#230]
We are trying to use `setup-ruby` on a self hosted runner but we get this error:

```
The environment variable ImageOS must be set
```

I tried all kinds of things but I can't get it working, this is our current yml file for our actions.

```yml
name: tests

on: [ push ]

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  rubocop:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 3.0.2
        if: steps.changes.outputs.stekkerweb == 'true'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
        env:
          ImageOS: ubuntu20
```

I see a mention of this issue in the readme, but it does not tell me what to do. Can someone give me a pointer on how to fix this? 

Thanks! ✨
