### ISSUE TITLE
ENOENT: no such file or directory, mkdir

### ISSUE THREAD

**Issue by cmer** [ruby/setup-ruby#263]
Running into an odd issue. Not quite sure what could be causing this?

<img width="487" alt="CleanShot 2022-01-16 at 13 53 17@2x" src="https://user-images.githubusercontent.com/412/149673738-8910d3ae-2cad-461b-ae0a-5aaba832da0e.png">

```
steps:
  - uses: actions/checkout@v2

  - name: Setup Ruby
    uses: ruby/setup-ruby@v1
    with:
      bundler: default
      bundler-cache: true
```

It happens on my self-hosted runner (Ubuntu 20.04) but doesn't happen on Github's runners.
