### ISSUE TITLE
Ruby 3.1 not available on ubuntu-latest

### ISSUE THREAD

**Issue by CodeMeister** [ruby/setup-ruby#286]
Specifying Ruby 3.1 with ubuntu-latest fails. 

```
 runs-on: ubuntu-latest
 strategy:
   matrix:
     ruby-version: ['3.1']
```

But failing with message:

```
Unknown version 3.1 for ruby on ubuntu-20.04
        available versions for ruby on ubuntu-20.04: 2.1.9, 2.2.10, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.9, 2.4.10, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.7.0, 2.7.1, 2.7.2, 3.0.0-preview1, 3.0.0-preview2, 3.0.0-rc1, 3.0.0, head, debug
```
