### ISSUE TITLE
self-hosted runner: Error: ENOENT: no such file or directory, mkdir

### ISSUE THREAD

**Issue by yegor256** [ruby/setup-ruby#296]
I'm trying to run this action with my self-hosted runner.

This is my configuration:

```yaml
jobs:
  build:
    runs-on: self-hosted
    env:
      ImageOS: ubuntu20
    steps:
      - run: sudo mkdir -p /opt/hostedtoolcache
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: false
```

This is the output I'm getting:

```
Run ruby/setup-ruby@v1
  with:
    ruby-version: 2.6
    bundler-cache: false
    bundler: default
    working-directory: .
    cache-version: 0
  env:
    ImageOS: ubuntu20
Modifying PATH
  Entries added to PATH to use selected Ruby:
    /opt/hostedtoolcache/Ruby/2.6.9/x64/bin
Error: ENOENT: no such file or directory, mkdir
```

It's unclear what file/dir it can't find. What should I do?
