### ISSUE TITLE
Skip `bundle install`

### ISSUE THREAD

**Issue by noraworld** [ruby/setup-ruby#297]
How can I skip `bundle install` at `ruby/setup-ruby@v1`?

I use `ruby/setup-ruby@v1` on GitHub Actions side (a repository side that `action.yml` exists), and use it at another repository. I would like GitHub Actions to install gems with `Gemfile` of **GitHub Actions side** (a repository side that `action.yml` exists), but it's actually used `Gemfile` of **workflow side** (a repository side that `.github/workflows/foo.yml` exists).

I believe this problem will be fixed if I could skip `bundle install` at `ruby/setup-ruby@v1` because it is possible to specify a file in which RubyGems I would like to install like this.

```yaml
    - name: Install RubyGems
      run: bundle install --gemfile=$GITHUB_ACTION_PATH/Gemfile
      shell: sh
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
```

But I'm not sure how I achieve this.

How can I fix this problem?

**Comment by MSP-Greg** [comment]
@noraworld

From the README, leading to action.yml (which describes the action's inputs):
```
  bundler-cache:
    description: 'Run "bundle install", and cache the result automatically. Either true or false.'
    required: false
    default: 'false'
```
So, I assume your workflow file is setting `bundler-cache: true` in the `setup-ruby` step?  Remove that, and `bundle install` is not run...
