### ISSUE TITLE
Can't install latest bundler for a specific minor version (e.g. 2.2.x)

### ISSUE THREAD

**Issue by Fryguy** [ruby/setup-ruby#304]
Let's say I want to install the latest bundler 2.2.x.

- If I pass `bundler: 2.2`, then it installs `2.3.x` because it generates the command `gem install bundler -v ~> 2.2`
- if I pass `bundler: 2.2.0`, then it installs `2.2.0`, and not the latest, because it generates the command `gem install bundler -v 2.2.0`.
- If I pass `bundler: 2.2.x` that is not valid input into the gem install command.
- I've also tried mangling the input in various ways to bypass the [regex](https://github.com/ruby/setup-ruby/blob/bd94d6a504586da892a5753afdd1480096ed30df/bundler.js#L98) that gates the `~>`, but those are detected as [invalid input](https://github.com/ruby/setup-ruby/blob/bd94d6a504586da892a5753afdd1480096ed30df/bundler.js#L68).

If there is no workaround, then this is an enhancement request to perhaps allow something like `bundler: 2.2.x`, which, if detected, would translate to `gem install bundler -v ~> 2.2.0`.

Example:

```yaml
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: 2.2.x
        bundler-cache: true
```
