### ISSUE TITLE
ruby setup error due to hardcoded username 'runner'

### ISSUE THREAD

**Issue by aditya-enthu** [ruby/setup-ruby#322]
https://github.com/ruby/setup-ruby/blob/eb938a806ed6dbfb36293b94ccb2afaf2d590c92/common.js#L131

As in above line, the user for macOS is runner which cannot be true in case of self-hosted runner.

Is there a way we can bypass this stage or correct it. Thank you in advance.

steps:
```
     - name: Setup Ruby 
        uses: ruby/setup-ruby@v1
        env:
          ImageOS: macos1015
        with:
          ruby-version: '2.6.8'
          bundler-cache: false
```

Error:

```
  ImageOS: macos1015
##[endgroup***
##[group***Modifying PATH
Entries removed from PATH to avoid conflicts with default Ruby:
  /usr/local/opt/ruby/bin
  /usr/local/opt/ruby/bin
Entries added to PATH to use selected Ruby:
  /Users/runner/hostedtoolcache/Ruby/2.6.8/x64/bin
##[endgroup***
##[error***Error: EACCES: permission denied, mkdir '/Users/runner'
```

Created user 'runner' but running job from other user end up in error too.

```
  ImageOS: macos1015
##[endgroup***
##[group***Modifying PATH
Entries removed from PATH to avoid conflicts with default Ruby:
  /usr/local/opt/ruby/bin
  /usr/local/opt/ruby/bin
Entries added to PATH to use selected Ruby:
  /Users/**runner**/hostedtoolcache/Ruby/2.6.8/x64/bin
##[endgroup***
##[error***Error: EACCES: permission denied, mkdir '/Users/runner/hostedtoolcache'
```
