### ISSUE TITLE
Action currently broken

### ISSUE THREAD

**Issue by RubenVerborgh** [ruby/setup-ruby#348]
https://github.com/SolidLabResearch/WhatsInAPod/runs/6881972637 gives

```
Error: Error: The process '/opt/hostedtoolcache/Ruby/2.6.10/x64/bin/bundle' failed with exit code 16
    at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:4918:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:4901:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:4795:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

with config

```
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby ✨
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
          cache-version: 1
```
