### ISSUE TITLE
bundler-cache doesn't work with different working-directories.

### ISSUE THREAD

**Issue by fsimonis** [ruby/setup-ruby#350]
Using the caching functionality of the action various times using different working-directories leads to incorrectly restored caches.

First workflow runs and caches `website/vendor/bundle`
```yml
- uses: ruby/setup-ruby@v1
  with:
    bundler-cache: true
    working-directory: website
```

Second workflow runs and restores the cache:
```yml
- uses: ruby/setup-ruby@v1
  with:
    bundler-cache: true
```
Then the cache gets restored in `website/vendor/bundle` instead of `vendor/bundle`.
`bundle install` runs normally as it is configured to use `vendor/bundle`

Example of the [second workflow](https://github.com/precice/precice.github.io/runs/7069802433?check_suite_focus=true). `jekyll build` fails here as it picks up files in `website/vendor/bundle`
