### ISSUE TITLE
What is the best way to install the Bundler version used in Gemfile.lock?

### ISSUE THREAD

**Issue by mediafinger** [ruby/setup-ruby#357]
In the README it says:

> Note that any step doing `bundle install` (for the root Gemfile) or `gem install bundler` can be removed with `bundler-cache: true`.

When we run our action with this setup:

```yaml
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.REPO_SCOPED_TOKEN }}
          BUNDLE_WITH: test
          BUNDLE_WITHOUT: development:staging:production
        with:
          bundler-cache: true
          cache-version: 1
```          

We frequently get errors like:

```
err: Warning: the running version of Bundler (2.2.33) is older than the version that created the lockfile (2.3.9). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.9`.
```

As stated in the error message, someone bundled locally with a recent version of Bundler and we have this on our Gemfile.lock:

```
BUNDLED WITH
   2.3.9
``` 

Nevertheless the setup-ruby action installs a different version of bundler (probably the default for Ruby 3.0.4 ?).

So, I'd say `bundler-cache: true` is not doing what I'd expect it to do. And I didn't find a BUNDLE_BUNDLER_VERSION config to pass it the version I'd like to install it.

What is the best way now to avoid this error and use the correct bundler version?  
When I want to keep `bundler-cache: true` how can I run `gem install bundler -v '2.3.9'`?
