### ISSUE TITLE
Once using self-hosted cannot switch back to cloud github runners

### ISSUE THREAD

**Issue by aradwyr** [ruby/setup-ruby#384]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
jobs:
  js-rb-dependencies:
    name: js-rb-dependencies
    runs-on: ubuntu-latest
    container:
      image: (image-name)
      credentials:
        username: ${{ secrets.DOCKERHUB_UNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    services:
      redis:
        image: redis:3.2
      mongo:
        image: mongo:4.0.8
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.1'
          bundler-cache: true 
          cache-version: 1.1
      - name: Install JS Dependencies
        run:  /usr/bin/yarn install
```

### Link to the log of a failed workflow job, or to a gist with the output

output below

### The command and output of the failing step

```shell
Error: Error: The environment variable ImageOS must be set

Error: Error: The environment variable ImageOS must be set
    at getImageOS (/__w/_actions/ruby/setup-ruby/v1/dist/index.js:398:11)
    at Module.getVirtualEnvironmentName (/__w/_actions/ruby/setup-ruby/v1/dist/index.js:415:19)
    at setupRuby (/__w/_actions/ruby/setup-ruby/v1/dist/index.js:66620:27)
    at run (/__w/_actions/ruby/setup-ruby/v1/dist/index.js:66603:11)
    at /__w/_actions/ruby/setup-ruby/v1/dist/index.js:66764:40
    at /__w/_actions/ruby/setup-ruby/v1/dist/index.js:66766:3
    at Object.<anonymous> (/__w/_actions/ruby/setup-ruby/v1/dist/index.js:66769:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

### Any other notes?

I've also tried bumping the cache-version and still seeing the same error
