### ISSUE TITLE
Error activating did_you_mean

### ISSUE THREAD

**Issue by goldstar611** [ruby/setup-ruby#389]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

`.ruby-version`

```
2.7.6
```

`Gemfile`

```
source "https://rubygems.org"

gem "did_you_mean"
```

`Gemfile.lock`

```
GEM
  remote: https://rubygems.org/
  specs:
    did_you_mean (1.6.1)

PLATFORMS
  ruby

DEPENDENCIES
  did_you_mean

BUNDLED WITH
   2.3.24
```

`.github/workflows/repro.yml`

```yaml
name: Repro

on:
  push: 
    branches: main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 1

      - name: Failhere
        run: |
         bundle exec rake db:migrate
```

### Link to the log of a failed workflow job, or to a gist with the output

https://github.com/goldstar611/setup-ruby-errors/actions/runs/3298370869/jobs/5440401485

### The command and output of the failing step

`bundle exec rake XXX`

```
bundler: failed to load command: rake (/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/rake)
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.24/lib/bundler/runtime.rb:308:in `check_for_activated_spec!': You have already activated did_you_mean 1.4.0, but your Gemfile requires did_you_mean 1.6.1. Since did_you_mean is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports did_you_mean as a default gem. (Gem::LoadError)
```

### Any other notes?

I have been using rbenv until I was told about this `setup-ruby` action. There are no issues with activating `did_you_mean` with rbenv.

This was first noticed on a self hosted runner using a different version of ruby, a different version of bundler and a different version of `did_you_mean`. 

I upgraded all of these versions and the problem still exists.
