### ISSUE TITLE
bundler-cache

### ISSUE THREAD

**Issue by navi86** [ruby/setup-ruby#413]
I noticed that I don't preserve folder "/opt/hostedtoolcache" on self-hosted runners, but still I am using cache
```
- name: ruby setup
      uses: ruby/setup-ruby@v1
      with:
        bundler: "Gemfile.lock"
        bundler-cache: true
```
Cache key: setup-ruby-bundler-cache-v4-ubuntu-20.04-ruby-2.7.5-Gemfile.lock-46776f0f030d8770f8e96
is it stored in GitHub ? Is it possible to store cache locally on runner ?
