### ISSUE TITLE
recent ruby-head builds do not run under valgrind

### ISSUE THREAD

**Issue by flavorjones** [ruby/setup-ruby#414]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
ruby-head-valgrind:
    needs: ["ruby-head"]
    strategy:
      fail-fast: false
      matrix:
        sys: ["enable", "disable"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: "head"
          apt-get: "libxml2-dev libxslt1-dev pkg-config valgrind"
          bundler-cache: true
          bundler: latest
      - uses: actions/cache@v3
        if: matrix.sys == 'disable'
        with:
          path: ports
          key: ports-ubuntu-${{hashFiles('dependencies.yml', 'patches/**/*.patch')}}
      - run: bundle exec rake compile -- --${{matrix.sys}}-system-libraries
      - run: bundle exec rake test:valgrind
```
```


### Link to the log of a failed workflow job, or to a gist with the output

https://github.com/sparklemotion/nokogiri/actions/runs/3655590659/jobs/6184133048

### The command and output of the failing step

```shell
When running valgrind on recent ruby-head builds, this error manifests:


==3138== Valgrind: debuginfo reader: ensure_valid failed:
==3138== Valgrind:   during call to ML_(img_get)
==3138== Valgrind:   request for range [1622332960, +4) exceeds
==3138== Valgrind:   valid image size of 39820208 for image:
==3138== Valgrind:   "/home/runner/.rubies/ruby-head/lib/libruby.so.3.2.0"
==3138== 
==3138== Valgrind: debuginfo reader: Possibly corrupted debuginfo file.
==3138== Valgrind: I can't recover.  Giving up.  Sorry.
==3138== 
```
```


### Any other notes?

This job has been running well for years. The most recent success was with `ruby 3.2.0dev (2022-11-29T15:09:32Z master 3e4d1a1dd1) [x86_64-linux]`, see https://github.com/sparklemotion/nokogiri/actions/runs/3581384598/jobs/6024628742

Has anything changed recently with how these versions were built?
