### ISSUE TITLE
Bugs in Version Syntax

### ISSUE THREAD

**Issue by rongxin-liu** [ruby/setup-ruby#432]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
on:
  - push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - run: echo "hello world"
```

### Link to the log of a failed workflow job, or to a gist with the output

https://github.com/rongxin-liu/ruby-workflow-test/actions/runs/3789566719/jobs/6443438026

### The command and output of the failing step

```shell
ruby/setup-ruby@v1
```

### Any other notes?

We specified the ruby version as `3.0`, but it used ruby version `3.2.0`. Shouldn't it be using the latest version of `3.0.x`?

<img width="974" alt="Screen Shot 2022-12-27 at 14 34 45" src="https://user-images.githubusercontent.com/10591665/209714371-16e6d4c0-d9c8-448a-a35b-2ff4c636e656.png">
