### ISSUE TITLE
Want to use ruby 3.2.0 with ubuntu 22.04

### ISSUE THREAD

**Issue by ttmthanh** [ruby/setup-ruby#434]
When I setup this:
```
- name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 3.2.0
          bundler-cache: true
```

I receive this error:
![image](https://user-images.githubusercontent.com/22828586/209939708-84648c86-c23e-413c-98c1-afe3e981451f.png)

Please help me choose version which compatible with ubuntu lastest. Because I found that ruby 3.0.1 too old.
Thank team!
