### ISSUE TITLE
How about changing interpretation of version string

### ISSUE THREAD

**Issue by znz** [ruby/setup-ruby#447]
Many users who wants use `3.0.x` write `ruby-version: 3.0` by mistake.

`3.0` interpreted as `3` on GitHub Actions.

For example, following workflow step prints `3` only.

```yaml
        env:
          env_var: 3.0
        run: |
          set -x
          echo ${env_var}
```

So I propose changing the meaning of `3` (and `3.0` on workflow files) use `3.0.x`, and `3.x` (or something) use latest `3.x.x`.

After this change, many users can write `3.0` intentionally, and some (probably less) users who want use latest `3.x.x` can write `3.x` or something instead.
