### ISSUE TITLE
perl version changes as side effect of this action

### ISSUE THREAD

**Issue by jwillemsen** [ruby/setup-ruby#454]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
name: windows

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rubysetupruby:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            ruby: '2.6'
            project_type: vs2019
          - os: windows-2019
            ruby: '3.0'
            project_type: vs2019
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ruby-${{ matrix.ruby }} ${{ matrix.project_type }}
    steps:
    - uses: actions/checkout@v3
    - name: perl before setup-ruby
      run: |
        which perl
        perl --version
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: perl after setup-ruby
      run: |
        which perl
        perl --version
  actionssetupruby:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            ruby: '2.6'
            project_type: vs2019
          - os: windows-2019
            ruby: '3.0'
            project_type: vs2019
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ruby-${{ matrix.ruby }} ${{ matrix.project_type }}
    steps:
    - uses: actions/checkout@v3
    - name: perl before setup-ruby
      run: |
        which perl
        perl --version
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: perl after setup-ruby
      run: |
        which perl
        perl --version
```

### Link to the log of a failed workflow job, or to a gist with the output

https://github.com/jwillemsen/setup-ruby-test/actions/runs/4037432209

### The command and output of the failing step

```shell
which perl
```

### Any other notes?

I tried to switch from `actions/setup-ruby` to `ruby/setup-ruby` some time ago and had some strange errors in some perl scripts we use. After trying to find the cause in our ruby code I found that when using `ruby/setup-ruby` the perl version changes silently. See the workflow code as reproducer, before executing `ruby/setup-ruby` perl is used from `/bin` but after it is from `/usr/bin`, see the attached logs. With `action/setup-ruby` this doesn't happen. 

[rubysetupruby.txt](https://github.com/ruby/setup-ruby/files/10530121/rubysetupruby.txt)
[actionsetupruby.txt](https://github.com/ruby/setup-ruby/files/10530122/actionsetupruby.txt)
