### ISSUE TITLE
Error: The process '/opt/hostedtoolcache/Ruby/3.1.2/x64/bin/bundle' failed with exit code 16 despite having added platform

### ISSUE THREAD

**Issue by joegaudet** [ruby/setup-ruby#457]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
name: Verify MasterFox
on:
  push:
    branches-ignore:
      - master
jobs:
  #  cancel:
  #    name: Cancel Previous Runs
  #    runs-on: ubuntu-latest
  #    timeout-minutes: 55
  #    steps:
  #      - name: cancel running workflows
  #        uses: everphone-gmbh/cancel-previous-workflows@v5
  #        env:
  #          GITHUB_TOKEN: ${{ github.token }}

  test-masterfox:
    runs-on: ubuntu-latest
    timeout-minutes: 55
    services:
      postgres:
        image: postgis/postgis:12-3.0
        ports: [ "5432:5432" ]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 10s --health-retries 10
        env:
          POSTGRES_USER: foxy
          POSTGRES_PASSWORD: test

      redis:
        image: redis:6.2
        ports: [ "6379:6379" ]

        options: --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --entrypoint redis-server

      elasticsearch:
        image: elasticsearch:7.16.3
        ports: [ "9200:9200" ]
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10 -e="xpack.security.enabled=false"


    env:
      TZ: America/Los_Angeles
      RAILS_ENV: test
      IS_CI: true,
      REDIS_URL: redis://localhost:6379/0
      ELASTICSEARCH_URL: http://localhost:9200
      DATABASE_URL: postgis://localhost:5432
      POSTGRES_USERNAME: foxy
      POSTGRES_PASS: tests
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Los_Angeles"

      - name: Decrypt .env file
        run: |
          # decrypt env vars
          gpg --batch --yes --passphrase="${GPG_SECRET}" --pinentry-mode loopback .env.ci.gpg
          mv .env.ci .env.test

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 2

      - name: Bundle install
        # Use the default PG 14 repository
        run: |
          sudo apt-get install libpq-dev postgresql-client-14 --fix-missing
          gem install bundler --version 2.2.31
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Checking Ruby Lint
        run: |
          bundle exec rubocop --force-exclusion -P

      - name: Test MasterFox
        run: |
          # Overwrite Legacy CI config
          mv config/database.gha.yml config/database.yml
          RAILS_ENV=test  bin/rails db:test:prepare
          IS_CI=true bin/rails test

      - name: Rename test report
        if: failure()
        run: |
          ls -la
          mv *.xml report.xml

      - name: Annotate Source
        if: failure()
        uses: Foodee/annotate-failing-tests@master
        with:
          report-file: report.xml
          language: ruby
          check-name: test-masterfox
          test-root: "MasterFox/test"

      - name: Cat Log
        if: failure()
        run: |
          cat log/test.log
```

### Link to the log of a failed workflow job, or to a gist with the output

https://gist.github.com/joegaudet/ae5ec60e4affdea000cd3c80031f0a0f

### The command and output of the failing step

```shell
- name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 2
```
```


### Any other notes?

The above job log includes the Gemfile.lock
