### ISSUE TITLE
Output from "env" potentially reveals secrets in the output

### ISSUE THREAD

**Issue by brcarp** [ruby/setup-ruby#464]
When running `ruby/setup-ruby@v1`, the actions output has a section for `with:` and a section for `env:`, the latter of which prints in plaintext any environment variables including ones that may have been set in the workflow to be pulled from repository or organizational secrets that are set by admins and not expected to be revealed to collaborators for security reasons.  (These can be imported into the workflow's environment using `${{ secrets.SECRET_NAME }}`.)

Is there any way that some environment variables can be designated as secrets such that their value can be redacted in the output that's otherwise visible to anyone who can run/view the actions (but may not be privy to all organizational secrets which might include authentication tokens)?

**Comment by dentarg** [comment]
I think that is just how GitHub Actions works?

It wont leak your secrets, GitHub knows what they are and hides the in the log:

```
Run ruby/setup-ruby@v1
  with:
    bundler-cache: true
    ruby-version: default
  env:
    BUNDLE_GITHUB__COM: x-access-token:***
```
