### ISSUE TITLE
Feature request: support `ruby-version: latest`

### ISSUE THREAD

**Issue by ybiquitous** [ruby/setup-ruby#465]
Hello. I have the motivation to always run a job with the latest Ruby version. Like this:

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: latest # implies '3.2' on Feb 2023
    - run: bundle exec rake
```

So, I suggest adding a new keyword `latest` that implies the latest Ruby version. If this were supported, we wouldn't need to rewrite a version like this once a new Ruby is released:

```diff
- ruby-version: '3.1'
+ ruby-version: '3.2'
```

This isn't absolutely necessary, but it would be helpful to people who maintain many Ruby workflows.

If there is a significant blocker to the realization of the feature, please don't hesitate to close this issue.

Thank you.
