### ISSUE TITLE
Action failing on ubuntu20

### ISSUE THREAD

**Issue by sebastianMagnaldi** [ruby/setup-ruby#471]
Hey ! I'm using this action on a self-hosted runner that is running ubuntu 20.4

This is how i'm defining the action in the yml

```
    - name: Set up Ruby from .ruby-version file
      uses: ruby/setup-ruby@v1
      env:
        ImageOS: ubuntu20
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
```

Before i was using this config and it was working perfectly fine. But then with the deprecation of ubuntu18 i had to update to ubuntu20 and it started failing : 

```
    - name: Set up Ruby from .ruby-version file
      uses: ruby/setup-ruby@v1
      env:
        ImageOS: ubuntu18
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
```

This is the error that i'm getting: 

```
An error occurred while installing ffi (1.15.5), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.15.5' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  cocoapods was resolved to 1.11.3, which depends on
    cocoapods-core was resolved to 1.11.3, which depends on
      typhoeus was resolved to 1.4.0, which depends on
        ethon was resolved to 0.16.0, which depends on
          ffi


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/ubuntu/actions-runner/_work/mobile/mobile/vendor/bundle/ruby/2.7.0/gems/unf_ext-0.0.8.2/ext/unf_ext
/opt/hostedtoolcache/Ruby/2.7.5/x64/bin/ruby -I
/opt/hostedtoolcache/Ruby/2.7.5/x64/lib/ruby/2.7.0 -r
./siteconf20230301-3399463-gfdj6u.rb extconf.rb
checking for -lstdc++... yes
creating Makefile

current directory:
/home/ubuntu/actions-runner/_work/mobile/mobile/vendor/bundle/ruby/2.7.0/gems/unf_ext-0.0.8.2/ext/unf_ext
make "DESTDIR=" clean

current directory:
/home/ubuntu/actions-runner/_work/mobile/mobile/vendor/bundle/ruby/2.7.0/gems/unf_ext-0.0.8.2/ext/unf_ext
make "DESTDIR="
compiling unf.cc
linking shared-object unf_ext.so

current directory:
/home/ubuntu/actions-runner/_work/mobile/mobile/vendor/bundle/ruby/2.7.0/gems/unf_ext-0.0.8.2/ext/unf_ext
make "DESTDIR=" install
make: /usr/bin/mkdir: Command not found
make: *** [Makefile:202: .sitearchdir.time] Error 127

make install failed, exit code 2

Gem files will remain installed in
/home/ubuntu/actions-runner/_work/mobile/mobile/vendor/bundle/ruby/2.7.0/gems/unf_ext-0.0.8.2
for inspection.
Results logged to
/home/ubuntu/actions-runner/_work/mobile/mobile/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/unf_ext-0.0.8.2/gem_make.out

An error occurred while installing unf_ext (0.0.8.2), and Bundler cannot
continue.
Make sure that `gem install unf_ext -v '0.0.8.2' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  fastlane was resolved to 2.211.0, which depends on
    faraday-cookie_jar was resolved to 0.0.7, which depends on
      http-cookie was resolved to 1.0.5, which depends on
        domain_name was resolved to 0.5.20190701, which depends on
          unf was resolved to 0.1.4, which depends on
            unf_ext
Error: The process '/opt/hostedtoolcache/Ruby/2.7.5/x64/bin/bundle' failed with exit code 5
Run npm uninstall -g yarn
/home/ubuntu/actions-runner/_work/_temp/7672c0d7-59b2-4337-a810-c5a7332[808](https://github.com/healthstarconnectsllc/mobile/actions/runs/4304708192/jobs/7506111391#step:3:819)cb.sh: line 1: npm: command not found
Error: Process completed with exit code 127.
```
Also i've tried to remove the env configuration in the action as follows: 
```
    - name: Set up Ruby from .ruby-version file
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
```
but then i get : `ImageOS enviroment variable must be set` and i think that's because the runner doesn't have the ImageOS variable configured but before setting the ImageOS in the action configuration worked as a charm.

- i've tried invalidating the cache but same issue.
- i've tried running the action with the following config and it worked: 

```
    - name: Set up Ruby from .ruby-version file
      uses: ruby/setup-ruby@v1.138.0
      env:
        ImageOS: ubuntu18
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
```
