### ISSUE TITLE
Support `--system` bundle install

### ISSUE THREAD

**Issue by thisismydesign** [ruby/setup-ruby#480]
My use case is setting up Ruby to use krane in the CI. I added a simple Gemfile in a subdirectory:

```
source 'https://rubygems.org'

gem 'activesupport'
gem 'krane'
```

I want these gems to be installed globally so I can use `krane` from the CLI

**Comment by dentarg** [comment]
What is stopping you exactly?

**Comment by thisismydesign** [comment]
If I do `gem install krane` I can interact with the `krane` CLI, but if I install dependencies via this action I can't:

```
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
```
