### ISSUE TITLE
Bundler seems to install wrong ruby version for ruby 3.1.3

### ISSUE THREAD

**Issue by marcuszierke** [ruby/setup-ruby#497]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

https://github.com/Setting-HQ/setting-highrise/actions/runs/4725694117/jobs/8384423884

### Any other notes?

```
Successfully installed bundler-2.4.12
Parsing documentation for bundler-2.4.12
Installing ri documentation for bundler-2.4.12
Done installing documentation for bundler after 0 seconds
1 gem installed
Your Ruby version is 3.1.4, but your Gemfile specified 3.1.3
Error: Process completed with exit code 18.
```

This error appears even tough the `.ruby-version` file defines `3.1.3` as well as hte `Gemfile` (ruby "3.1.3"). Even specifying the ruby version in the `actions.yml` (`with: ...`) produce this error.

**Comment by dentarg** [comment]
> ### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)
> https://github.com/Setting-HQ/setting-highrise/actions/runs/4725694117/jobs/8384423884

Not public

**Comment by marcuszierke** [comment]
It's my clients repo so I won't be able to make it public. But the error occurs nevertheless :) Maybe the `actions.yml` helps (credentials are asterisk):

```
name: 'Ruby on Rails CI'
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Lint Ruby files
        run: bin/rubocop --parallel

  test:
    needs: lint
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: ***
          POSTGRES_USER: ***
          POSTGRES_PASSWORD: ***

    env:
      RAILS_ENV: test
      DATABASE_URL: 'postgres://rails:password@localhost:5432/rails_test'

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.20.0
      - name: Install libvips
        run: sudo apt-get install -y libvips
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          yarn install
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run model tests
        run: bin/rails test test/models/
```
