### ISSUE TITLE
Can't install bundler with 2.7

### ISSUE THREAD

**Issue by matthewford** [ruby/setup-ruby#512]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

can't

### Any other notes?

This is my action:

```
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.7', '3.0']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: 2.4.15
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
```
3.0 installs bundler ok, but 2.7 fails with this error:
```
Installing Bundler
  /opt/hostedtoolcache/Ruby/2.7.7/x64/bin/gem install bundler -v 2.4.15
  Error: The operation was canceled.
```
