### ISSUE TITLE
Authenticate to GH Package Registry

### ISSUE THREAD

**Issue by kimegede** [ruby/setup-ruby#515]
Add possibility to pass a Personal Access Token to authenticate to GitHub Package Registry.

**Comment by dentarg** [comment]
You can just set the environment variable

**Comment by kimegede** [comment]
Okay, I have tried with the following:
But still required token it set.
```yaml
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
        env:
          BUNDLE_GITHUB__COM: ${{ secrets.GH_PACKAGE_TOKEN }}:x-oauth-basic
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.GH_PACKAGE_TOKEN }}
```

Currently using:

```yaml
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          bundle config set --global rubygems.pkg.github.com ${{ secrets.GH_PACKAGE_TOKEN }}:x-oauth-basic
          gem install bundler
          bundle install --jobs 4 --retry 3
```
