### ISSUE TITLE
Automated Bundler caching

### ISSUE THREAD

**Issue by eregon** [ruby/setup-ruby#52]
I'd like to add automated Bundler caching in this action, since caching manually like https://github.com/ruby/setup-ruby/blob/master/README.md#caching-bundle-install is quite verbose and hard to get right (e.g., https://github.com/sass/sassc-ruby/issues/183#issuecomment-622357550).

It would be optional, not sure about the default yet.

For that to work, we need `actions/cache` to be a package, so this needs https://github.com/actions/cache/issues/55 first.

**Comment by eregon** [comment]
WIP in branch `automated-bundler-caching`

**Comment by eregon** [comment]
#56 is merged, currently it's opt-in:
```yaml
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
```

**Comment by DannyBen** [comment]
Is this already deployed and should work?

With this step:

```yaml
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with: 
        ruby-version: '${{ matrix.ruby }}'
        bundler-cache: true
```

I am getting an error:

```
##[warning]Unexpected input(s) 'bundler-cache', valid inputs are ['ruby-version', 'version']
```
