### ISSUE TITLE
Duplicate cache, cache does not work

### ISSUE THREAD

**Issue by pepestupid** [ruby/setup-ruby#687]
### Ensure the following before filing this issue

- [x] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [x] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

it's a private repo

### Any other notes?

![Image](https://github.com/user-attachments/assets/6f67196e-73d7-4844-b811-c73a15e5530a)

```yaml
- name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.1'
        bundler-cache: true
```
