### ISSUE TITLE
Cache doesn't work with AWS Codebuild

### ISSUE THREAD

**Issue by saada** [ruby/setup-ruby#725]
### Ensure the following before filing this issue

- [x] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [x] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

self-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

N/A

### Any other notes?

I noticed the cache keys use the working directory as part of the key.

Unfortunately, when using AWS Codebuild runners, each run spins up in a new working directory. We cannot switch outside that directory. Which means no cache hits ever.

https://stackoverflow.com/questions/78775576/aws-codebuild-as-github-actions-runner-change-folder

Would it be possible to make the cache key configurable somehow? Or revert this [commit](https://github.com/headius/setup-ruby/commit/f60ef1e8084a2e64569f928c3f1cfac6c7e12ad7)

**Comment by eregon** [comment]
It's necessary for correctness for https://github.com/ruby/setup-ruby/issues/350.
I would consider it a bug of AWS CodeBuild, it seems pretty terrible for caching in general to always change the working directory.

**Comment by saada** [comment]
Why is providing a configurable option not something that can be supported?
Seems like something that is good for folks to have control over

**Comment by saada** [comment]
As a workaround for anyone else who hits this

```yaml
    - name: Set up Ruby
      id: setup-ruby
      uses: ruby/setup-ruby@v1
      with:
        # we cannot rely on the default caching approach due to
        # https://github.com/ruby/setup-ruby/issues/725
        bundler-cache: false

    - name: Cache Ruby Gems
      id: cache-gems
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ steps.setup-ruby.outputs.ruby-prefix }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-${{ steps.setup-ruby.outputs.ruby-prefix }}-
          ${{ runner.os }}-gems-

    - name: Bundle install
      shell: bash
      run: |
        bundle config path vendor/bundle
        bundle install --jobs $(nproc) --retry 3
```
