### ISSUE TITLE
Please consider BUNDLE_GEMFILE env variable

### ISSUE THREAD

**Issue by bquorning** [ruby/setup-ruby#73]
The current version (5a76bd6a5fe27d6e6e8af1f2e605f46d17557049) of the readme says

> By default, if there is a `Gemfile.lock` file with a `BUNDLED WITH` section,
> the latest version of Bundler with the same major version will be installed.
> Otherwise, the latest Bundler version is installed (except for Ruby 2.2 and 2.3 where only Bundler 1 is supported).
>
> This behavior can be customized, see action.yml for details about the `bundler` input.

When doing gem development it’s not uncommon to have CI testing various combinations of gem dependencies, for example 
 testing a Rails-specific library against e.g. Rails v4.2, v5.2 and v6.0.

To accomplish this, I usually have a `gemfiles` folder containing a number of gemfiles, and I would configure GitHub Actions like this:

```yaml
strategy:
  matrix:
    gemfile:
      - gemfiles/rails4.2.gemfile
      - gemfiles/rails5.2.gemfile
      - gemfiles/rails6.0.gemfile
steps:
  - uses: actions/checkout@v2
  - uses: ruby/setup-ruby@v1
  - run: echo "::set-env name=BUNDLE_GEMFILE::$GITHUB_WORKSPACE/${{ matrix.gemfile }}"
  …
```

Since I wouldn’t add Gemfile.lock to the repository, `ruby/setup-ruby` will automatically install Bundler v2 for all three gemfiles. And since [Rails 4.2](https://rubygems.org/gems/rails/versions/4.2.11.3) is restricted to versions `>= 1.3.0, < 2.0` of Bundler, my tests cannot run.

Would it be possible to change `ruby/setup-ruby` to consider the contents of `$BUNDLE_GEMFILE + ".lock"` before Gemfile.lock (when `$BUNDLE_GEMFILE` exists)?

Notes:

- `BUNDLE_GEMFILE` is mentioned in https://bundler.io/v2.1/man/bundle-config.1.html
- There is a tool for testing with multiple gemfiles, called “Appraisal”. It seems to work by [setting BUNDLE_GEMFILE](https://github.com/thoughtbot/appraisal/blob/586864393e405a67b1457b563a4d5adc99e50e2d/lib/appraisal/command.rb#L36) before each run.
